version: 2
updates:
  - package-ecosystem: npm
    directory: /cdk
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      aws-cdk:
        patterns:
          - "aws-cdk"
          - "aws-cdk-lib"
          - "constructs"
          - "@aws-cdk/*"
      dev-deps:
        dependency-type: development

  - package-ecosystem: terraform
    directory: /terraform/bootstrap
    schedule:
      interval: weekly
  - package-ecosystem: terraform
    directory: /terraform/modules/tags
    schedule:
      interval: weekly
  - package-ecosystem: terraform
    directory: /terraform/envs/shared-use1
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
